theme: jekyll-theme-minimal #https://github.com/pages-themes/minimal
title: MDC Modding Wiki
description: An open source modding tutorial wiki
logo: logo.png
include: CONTRIBUTING.md
defaults:
  -
    scope:
      path: "" # All files in the project
    values:
      layout: "default"